spring:
  profiles:
    active: test
    
---
spring:
  thymeleaf:
    cache: false
  main:
    banner-mode: 'off' 


server:
  tomcat:
    access_log_enabled: true
  port: 8089



---
spring:
  profiles: test



---
  
spring:
  profiles: cible
  
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

server:
  port: ${SERVER_APP_PORT}
  
  
---
spring:
  profiles: prod
  
  
