#Common properties

spring:
  profiles:
    active: test
    
# Datasource
# ===============
# Embedded tomcat/H2

# ===============
# JPA / HIBERNATE
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    
server:
  tomcat:
    access_log_enabled: true
  port: 8059


---
spring:
  profiles: test


---
spring:
  profiles: cible
  main:
    web-environment: false
  datasource:
    url: jdbc:mysql://10.10.1.5:13306/BDProject?useSSL=false
    username: ptcNikeDB
    password: P0kl@vers!NikeDB


server:
  port: 18851


---
spring:
  profiles: prod
  main:
    web-environment: false
  datasource:
    url: jdbc:mysql://10.10.1.5:13306/BDProject?useSSL=false
    username: ptcNikeDB
    password: P0kl@vers!NikeDB
    # Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery: SELECT 1
